jdbc.url=jdbc:mysql://localhost/student?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
user=root
password=123
driverClass=com.mysql.cj.jdbc.Driver